spring:
  security:
    oauth2:
      client:
        registration:
#          google:
#            client-id: ${OAUTH2_GOOGLE_CLIENT_ID}
#            client-secret: ${OAUTH@_GOOGLE_CLIENT_SECRET}
#            redirect-uri: "{baseUrl}/login/oauth2/code/google"
#            scope:
#              - email
#              - profile
#            authorization_grant_type: authorization_code
#            client_name: Google
          kakao:
            client-id: ${OAUTH2_KAKAO_CLIENT_ID}
            client-secret: ${OAUTH2_KAKAO_CLIENT_SECRET}
            redirect-uri: ${KAKAO_REDIRECT_URL}
            scope:
              - profile
              - account_email
            authorization_grant_type: authorization_code
            client_name: Kakao
#          naver:
#            client-id: ${OAUTH2_NAVER_CLIENT_ID}
#            client-secret: ${OAUTH2_NAVER_CLIENT_SECRET}
#            redirect-uri: "{baseUrl}/login/oauth2/code/naver"
#            scope:
#              - name
#              - email
#            authorization_grant_type: authorization_code
#            client_name: Naver
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
#          naver:
#            authorization-uri: https://nid.naver.com/oauth2.0/authorize
#            token-uri: https://nid.naver.com/oauth2.0/token
#            user-info-uri: https://openapi.naver.com/v1/nid/me
#            user-name-attribute: response.id

#JWT config
jwt:
  secret: JWT_SECRET
  issuer: JWT_ISSUER
  token:
    access-expiration: 1800000
    refresh_expiration: 604800000